<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<RootNamespace />
    <PackageTags>DI IoC DependencyInjection Blazor</PackageTags>
	<Description>This is for the Blazor server-side project and provides a setup method to ensure that you can use the static property PinnedScope.ScopedServices.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="[9.0.0, 10.0.0)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DependencyInjection.StaticAccessor.Hosting\DependencyInjection.StaticAccessor.Hosting.csproj" />
  </ItemGroup>

</Project>
