<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../common.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageTags>DI IoC DependencyInjection</PackageTags>
	<Description>Provide a static property PinnedScope.ScopedServices that allows you to get the IServiceProvider instance within the current scope from anywhere.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
  </ItemGroup>

</Project>
