name: Publish Prerelease NuGets
on:
  push:
    branches:
      - pre/*
env:
  TIMESTAMP: $(date +'%s')
  SOLUTION: DependencyInjection.StaticAccessor.sln
jobs:
  publish:
    name: Build and Publish
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x

      - name: Remove Tests
        run: dotnet sln ${{ env.SOLUTION }} remove (ls -r test/**/*.csproj)

      - name: Restore NuGets
        run: dotnet restore ${{ env.SOLUTION }}
        
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore ${{ env.SOLUTION }} --version-suffix preview-${{ env.TIMESTAMP }}

      - name: Delete exists packages
        run: Remove-Item -Path nugets -Recurse -Force -ErrorAction SilentlyContinue

      - name: Pack Solution
        run: dotnet pack ${{ env.SOLUTION }} --configuration Release --no-build --version-suffix preview-${{ env.TIMESTAMP }}

      - name: Publish
        run: |
          $branchName = "${{ github.ref_name }}"

          if ($branchName -eq "pre/wasm") {
            $pkgs = @("DependencyInjection.StaticAccessor.Blazor.WebAssembly")
          } elseif ($branchName -eq "pre/blazor") {
            $pkgs = @("DependencyInjection.StaticAccessor.Blazor", "DependencyInjection.StaticAccessor.Blazor.WebAssembly")
          } elseif ($branchName -eq "pre/hosting") {
            $pkgs = @("DependencyInjection.StaticAccessor.Hosting")
          } elseif ($branchName -eq "pre/basic") {
            $pkgs = @("DependencyInjection.StaticAccessor", "DependencyInjection.StaticAccessor.Hosting")
          }

          foreach ($pkg in $pkgs) {
            $p = ($pkg -replace "\.", "\.") + "\.\d+\.\d+\.\d+-preview-\d+\.nupkg"
            $nupkg = Get-ChildItem -Path nugets | Where-Object { $_.Name -match $p }
            dotnet nuget push $nupkg.FullName -k ${{ secrets.API_KEY }} -s https://api.nuget.org/v3/index.json
          }
